version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
    labels:
      - "dependencies"
      - "dependabot"
  - package-ecosystem: "npm"
    directory: "/sample_subject"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
    labels:
      - "dependencies"
      - "sample-subject"
